baseURL = "https://mizzunet.eu.org/gocolly/"
languageCode = "en-us"
title = "Colly"
theme = "colly"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
enableRobotsTXT = false
pygmentsCodeFences = true
#pygmentsOptions = "linenos=true"

[params]
  title = "Colly"
  description = "Scraping Framework for Golang"
  github = "https://github.com/gocolly/colly"

[[menu.main]]
  name = "Docs"
  url = "/docs/"
  weight = 10
  identifier = "docs"

[[menu.main]]
  name = "Articles"
  url = "/articles/"
  weight = 15
  identifier = "articles"

[[menu.main]]
  name = "Services"
  url = "/services/"
  weight = 21
  identifier = "services"

[[menu.main]]
  name = "Datasets"
  url = "/datasets/"
  weight = 30
  identifier = "datasets"


[[menu.docs]]
  name = "Introduction"
  url = "/docs/introduction/"
  weight = 10
  identifier = "introduction"


[[menu.docs]]
  name = "Best Practices"
  url = "/docs/best_practices/"
  weight = 15
  identifier = "best_practices"

[[menu.docs]]
  name = "Examples"
  url = "/docs/examples/"
  weight = 20
  identifier = "examples"

[[menu.docs]]
  name = "Real life examples"
  url = "/docs/real_examples/"
  weight = 20
  identifier = "real_examples"
